### ISSUE TITLE
Socket connection shouldn't work in the SSR server

### ISSUE THREAD

**Issue by marshallswain** [stealjs/steal-socket.io#5]
I see that this is stubbed out to `@empty` in the server, but this is actually running in the bitcentive SSR, server.  Maybe we can take a look at why that's the case @matthewp

**Comment by matthewp** [comment]
Do you want it running in the bitcentive server?

**Comment by marshallswain** [comment]
No.  I want it to no-op, still.

**Comment by marshallswain** [comment]
This seems to be working properly, now.  It was probably an environment issue.
